#!/usr/bin/env bash
# Pre-flight for ANY nginx change on this VM. Run it before `nginx -t`, not after.
#
# WHY THIS EXISTS
# `/etc/nginx/sites-enabled/*` and `/etc/nginx/conf.d/*.conf` are GLOBBED. A
# backup left beside a real file is loaded as configuration. This has already
# cost one repair cycle: a script backed up `sites-enabled/traycer` to
# `sites-enabled/traycer.bak.<timestamp>`, nginx loaded both, and the resulting
# duplicate `server_name` produced:
#
#   [emerg] could not build server_names_hash, you should increase
#           server_names_hash_bucket_size: 64
#
# That message names neither the duplicate nor the backup, and raising the
# bucket size — the obvious reading — does not help. An hour can go into
# chasing the symptom.
#
# `conf.d/` carries the identical hazard with an even more opaque failure: a
# duplicated `limit_req_zone` is a plain "duplicate zone" error naming the zone,
# not the stray file that redefined it.
#
# So this script asserts the directories contain ONLY what belongs there, and
# names the offender. It fails at the author, in the seconds before their
# change, rather than at whoever next reloads.
#
# Usage: verify-nginx-hygiene.sh            (check only)
#        verify-nginx-hygiene.sh --quarantine  (move offenders to /root/nginx-backups/)
set -uo pipefail

QUARANTINE_DIR=/root/nginx-backups
DO_QUARANTINE=0
[ "${1:-}" = "--quarantine" ] && DO_QUARANTINE=1

# The complete expected set. Deliberately an explicit allowlist rather than a
# pattern: "everything that isn't obviously a backup" would pass the next
# unexpected file, and unexpected is the whole problem.
#   sites-enabled/traycer          the one server config (bootstrap.sh generates it)
#   conf.d/traycer-limits.conf     rate-limit zones (http-level, must load first)
#   conf.d/traycer-upstream.conf   generated by traycer-nginx-upstream.sh from pid.json
EXPECTED_SITES="traycer"
EXPECTED_CONFD="traycer-limits.conf traycer-upstream.conf"

offenders=()

scan() {
  local dir="$1" expected="$2" glob="$3"
  [ -d "$dir" ] || return 0
  local f base
  for f in "$dir"/$glob; do
    [ -e "$f" ] || continue
    base="$(basename "$f")"
    if ! printf '%s\n' $expected | grep -qxF "$base"; then
      offenders+=("$f")
      # A best-effort hint at why it's here, since the author usually knows the
      # word "bak" but not that the directory is globbed.
      case "$base" in
        *.bak*|*.orig|*.save|*~|*.old|*.dpkg-*|*.disabled)
          echo "UNEXPECTED  $f   <- looks like a backup; nginx LOADS this" ;;
        *)
          echo "UNEXPECTED  $f   <- not in the expected set for this VM" ;;
      esac
    fi
  done
}

echo "--- /etc/nginx/sites-enabled (globbed by 'include sites-enabled/*') ---"
scan /etc/nginx/sites-enabled "$EXPECTED_SITES" '*'
echo "--- /etc/nginx/conf.d (globbed by 'include conf.d/*.conf') ---"
# Only *.conf is globbed here, so a `foo.conf.bak` is harmless while a
# `foo.bak.conf` is not. Scan *.conf specifically rather than everything, or
# this reports files nginx never reads.
scan /etc/nginx/conf.d "$EXPECTED_CONFD" '*.conf'

if [ ${#offenders[@]} -eq 0 ]; then
  echo "OK: no unexpected globbed files"
else
  echo
  echo "${#offenders[@]} unexpected file(s) WILL BE LOADED as config."
  if [ "$DO_QUARANTINE" -eq 1 ]; then
    mkdir -p "$QUARANTINE_DIR"
    for f in "${offenders[@]}"; do
      mv -v "$f" "$QUARANTINE_DIR/"
    done
    echo "Moved to ${QUARANTINE_DIR} (outside every globbed directory)."
  else
    echo "Re-run with --quarantine to move them to ${QUARANTINE_DIR}, or move them yourself."
    echo "Do NOT back up into sites-enabled/ or conf.d/ - that is what causes this."
  fi
fi

echo
echo "--- nginx -t ---"
if nginx -t 2>&1; then
  echo "CONFIG OK"
else
  status=$?
  echo "CONFIG INVALID (exit ${status})."
  if [ ${#offenders[@]} -gt 0 ]; then
    echo "NOTE: the unexpected files above are the most likely cause."
    echo "      A 'server_names_hash_bucket_size' or 'duplicate zone' error is"
    echo "      usually a SYMPTOM of a duplicate block, not a sizing problem."
  fi
  exit 1
fi

[ ${#offenders[@]} -eq 0 ] || exit 1
exit 0
