#!/usr/bin/env bash
# Publishes `/api/messages` so Azure Bot Service can reach the bot on
# loopback:3978.
#
# SUPERSEDES the ingress half of vm-nginx-route.sh / vm-nginx-fix.sh /
# vm-nginx-fix2.sh. Those three splice the location block into
# /etc/nginx/sites-enabled/traycer, which infra/azure/scripts/bootstrap.sh
# REGENERATES WHOLESALE — so the route they add is erased by the next
# bootstrap run or VM rebuild, silently, with nothing in any diff to explain
# why the bot stopped receiving activities. They remain in the tree because
# they carry findings this file does not (the duplicate-server-block trap in
# fix2, the credentials-ownership repair in fix), but the ROUTE is now here.
#
# The mechanism, and why it is not in bootstrap.sh, is written out once in
# clients/teams-tab/deploy/vm-serve-tab.sh — this file is deliberately its
# twin. Short version:
#
#   * the route lives in /etc/nginx/traycer-locations.d/, which bootstrap.sh
#     does not generate and therefore cannot clobber;
#   * the vhost gains one GENERIC `include` line, so bootstrap.sh stays
#     Teams-agnostic — which is what main.bicep's own scope comment says it
#     should be;
#   * this script inserts that include itself rather than depending on
#     bootstrap.sh already carrying it, so it is correct on the CURRENT live
#     box, whose vhost has no include line. A drop-in nginx never reads is an
#     outage, and the fix must not be the outage;
#   * the ~20 duplicated lines are forced by `az vm run-command invoke`, which
#     delivers one inlined script with no second file to source.
#
# ⚠️ A ROUTE IS NOT A DEPLOYMENT. This script publishes the path. The unit,
# the bundle, the identity registry and the secret come from vm-deploy.sh and
# vm-write-secret.sh, none of which are in the IaC either. On a rebuilt VM
# this route proxies to a closed port and returns 502. That is honest and it
# is not "the bot is back".
set -euo pipefail

# Hostname is deployment-specific: never hardcoded in an OSS repo.
if [ -z "${PUBLIC_HOSTNAME:-}" ]; then
  echo "PUBLIC_HOSTNAME is required" >&2; exit 1
fi

SITE=/etc/nginx/sites-enabled/traycer
DROPIN_DIR=/etc/nginx/traycer-locations.d
DROPIN="$DROPIN_DIR/teams-bot.conf"

mkdir -p "$DROPIN_DIR"

changed=0

# --- 1. the include line ---------------------------------------------------
if grep -q 'traycer-locations.d' "$SITE"; then
  echo "nginx: drop-in include already present"
else
  # Backup goes OUTSIDE sites-enabled — nginx globs that directory, so a
  # backup left beside the config loads as a SECOND server block. That is
  # precisely what vm-nginx-fix2.sh exists to repair; do not recreate it.
  mkdir -p /root/nginx-backups
  cp "$SITE" "/root/nginx-backups/traycer.$(date +%s).bak"

  awk '
    !ins && /^[[:space:]]*location \/ \{/ {
      print "    # Routes owned by clients that bootstrap.sh does not generate"
      print "    # (Teams tab, Teams bot). Kept out of the vhost body because"
      print "    # bootstrap.sh rewrites this file wholesale."
      print "    include /etc/nginx/traycer-locations.d/*.conf;"
      print ""
      ins = 1
    }
    { print }
  ' "$SITE" > /tmp/traycer.new

  if ! grep -q 'traycer-locations.d' /tmp/traycer.new; then
    echo "INSERT FAILED — no 'location / {' anchor matched; config untouched" >&2
    exit 1
  fi
  cp /tmp/traycer.new "$SITE"
  changed=1
  echo "nginx: drop-in include inserted"
fi

# --- 2. the /api/messages location -----------------------------------------
#
# On a box whose vhost still carries the OLD spliced block, leave it: two live
# `location /api/messages` blocks are a duplicate and `nginx -t` rejects the
# pair. The spliced one keeps working until bootstrap regenerates the vhost —
# the exact event this defends against — and the drop-in is what survives it.
if grep -q 'location /api/messages' "$SITE"; then
  echo "nginx: /api/messages is spliced into the vhost (pre-drop-in box) — left as is"
  echo "       it will be replaced by the drop-in when bootstrap regenerates"
elif [ -f "$DROPIN" ]; then
  echo "nginx: /api/messages drop-in already present"
else
  cat > "$DROPIN" <<'BOT_LOCATION'
# Azure Bot Service -> the bot's HTTP listener on loopback.
#
# Installed by clients/teams-bot/deploy/vm-bot-ingress.sh. NOT generated by
# bootstrap.sh, and neither is the service behind it: on a rebuilt VM this
# returns 502 until vm-deploy.sh + vm-write-secret.sh have run.
#
# `/healthz` is deliberately NOT published — the bot's health endpoint stays
# on loopback, so a public GET /healthz correctly 404s from nginx.
location /api/messages {
    proxy_pass http://127.0.0.1:3978/api/messages;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 1m;
}
BOT_LOCATION
  changed=1
  echo "nginx: /api/messages drop-in written to $DROPIN"
fi

# --- 3. gate, then reload --------------------------------------------------
#
# `nginx -t` tested DIRECTLY, not through a pipe: `nginx -t | tail` reports
# tail's exit status in bash unless `pipefail` happens to be set, and a
# safety gate should not depend on a shell option set 60 lines away. This
# server block also fronts the live host's /rpc and /stream, so a bad reload
# takes those down too.
if [ "$changed" -eq 0 ]; then
  echo "nginx: nothing changed — no reload"
else
  if ! nginx -t 2>/tmp/nginxt.log; then
    echo "nginx -t FAILED — rolling back" >&2
    cat /tmp/nginxt.log >&2
    rm -f "$DROPIN"
    latest="$(ls -t /root/nginx-backups/traycer.*.bak 2>/dev/null | head -1)"
    [ -n "$latest" ] && cp "$latest" "$SITE"
    nginx -t
    exit 1
  fi
  systemctl reload nginx
  echo "nginx: reloaded"
fi

echo "=== nginx test ==="
nginx -t 2>&1 | tail -2
echo "=== drop-ins ==="
ls -la "$DROPIN_DIR"
echo "=== public probes through real TLS ==="
# 403 is the PASS here: it means the request reached the Node process and the
# Bot Framework JWT gate rejected it. 502 means the route is up but the unit
# is not — the rebuilt-VM state. 404 means the route itself is missing.
curl -s -m 10 -o /dev/null -w "GET  /healthz        (expect 404 — deliberately not public): %{http_code}\n" \
  "https://${PUBLIC_HOSTNAME}/healthz" || true
curl -s -m 10 -X POST -o /dev/null -w "POST /api/messages   (expect 403 = reached the bot and was rejected): %{http_code}\n" \
  -H "content-type: application/json" -d '{"type":"message"}' \
  "https://${PUBLIC_HOSTNAME}/api/messages" || true
curl -s -m 10 -o /dev/null -w "GET  /rpc            (must still be reachable): %{http_code}\n" \
  "https://${PUBLIC_HOSTNAME}/rpc" || true
