/**
 * Emits `dist/web/sw.js` from `src/web/sw.ts` after a web build.
 *
 * WHY A POST-BUILD STEP RATHER THAN A VITE PLUGIN. The precache list can only
 * be read from the FINISHED `index.html` - the content hashes in the asset
 * names do not exist before then - and the worker's build id is derived from
 * that list. A plugin would have to run in `closeBundle` and do exactly this,
 * with the extra job of pretending to be part of a build it structurally comes
 * after. A script that runs second says what it is.
 *
 * WHY NO BUNDLER. `sw.ts` has no imports, so stripping types is the entire
 * transform, and `typescript` is already a root dependency of this repo. Adding
 * `vite-plugin-pwa` + `workbox-build` + `workbox-precaching` for this would
 * mean three dependencies, a `bun install` on a workspace whose lockfile is
 * already known to be stale, and a peer-range negotiation against Vite 8 - all
 * to generate a file this script generates in forty lines.
 *
 * THE BUILD ID IS CONTENT-DERIVED, and that is the load-bearing property.
 * A browser decides whether to install a new worker by BYTE-COMPARING the
 * script. Stamp it with a timestamp and every deploy prompts every user to
 * refresh, including a deploy that changed nothing. Stamp it with nothing and
 * a deploy that changed every asset might not prompt at all. Hashing the asset
 * list AND this worker's source makes "the bytes changed" mean exactly "the
 * app changed".
 *
 * Usage:  node tools/build-sw.mjs <distDir> <base>
 *   e.g.  node tools/build-sw.mjs dist/web /next/
 */
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import ts from "typescript";

/** Transpiles one self-contained `.ts` file to JS. No module resolution involved. */
async function transpile(path, module) {
  const source = await readFile(path, "utf8");
  return ts.transpileModule(source, {
    compilerOptions: { target: ts.ScriptTarget.ES2022, module },
    fileName: path,
  }).outputText;
}

/**
 * Loads `precache-list.ts` as a module without writing a temp file or adding a
 * loader. The alternative - a second copy of the URL-collection logic in this
 * script - is the thing that produced the staleness incident that module
 * exists to prevent, so it is worth the one unusual import.
 */
async function loadPrecacheList(mobileRoot) {
  const js = await transpile(
    resolve(mobileRoot, "src/web/precache-list.ts"),
    ts.ModuleKind.ESNext,
  );
  const url = `data:text/javascript;base64,${Buffer.from(js, "utf8").toString("base64")}`;
  return import(url);
}

/**
 * Type-strips `sw.ts` and injects `precache` - the exact operation `main()`
 * performs, exported so the test drives THIS function rather than a second
 * copy of it. A test that re-implemented the injection would agree with itself
 * about a worker the build never produced.
 */
export async function buildServiceWorkerText(mobileRoot, precache) {
  const swJs = await transpile(
    resolve(mobileRoot, "src/web/sw.ts"),
    ts.ModuleKind.None,
  );
  return generateServiceWorker(swJs, precache);
}

/**
 * The generated worker text: injected constants first, then the type-stripped
 * source.
 */
export function generateServiceWorker(swJs, precache) {
  // Sorted before it is either hashed OR injected, so one set of assets always
  // produces one set of bytes. Hashing a sorted list while injecting an
  // unsorted one would give a stable build id inside a file whose text still
  // moved - and the browser compares the TEXT, so a reordering that changed
  // nothing would prompt every user to refresh.
  const urls = [...precache].sort();

  const buildId = createHash("sha256")
    .update(urls.join("|"))
    .update(" ")
    .update(swJs)
    .digest("hex")
    .slice(0, 12);

  const header = [
    "// GENERATED by clients/mobile/tools/build-sw.mjs - do not edit.",
    "// Source: clients/mobile/src/web/sw.ts",
    // `sw` is `self`. It is bound here rather than in the source because
    // lib.webworker types `self` as `WorkerGlobalScope & typeof globalThis`,
    // which has neither `skipWaiting` nor service-worker event types - and the
    // only way to say so in the source is a double assertion, which this
    // package's lint rules ban. `sw.ts` declares the type; this supplies the
    // value. See that file's docblock.
    "const sw = self;",
    `const __TRAYCER_SW_BUILD_ID__ = ${JSON.stringify(buildId)};`,
    `const __TRAYCER_SW_PRECACHE__ = ${JSON.stringify(urls)};`,
    "",
  ].join("\n");

  return { buildId, precache: urls, text: `${header}${swJs}` };
}

async function main() {
  const [distArg = "dist/web", baseArg] = process.argv.slice(2);
  // Falls back to the SAME env var the Vite config reads, so the two cannot
  // disagree about where the app is served from. A worker built for `/` and an
  // app served at `/next/` would precache four 404s and never install.
  const base = baseArg ?? process.env.TRAYCER_WEB_BASE;
  if (base === undefined || base.trim().length === 0) {
    throw new Error(
      "usage: node tools/build-sw.mjs [distDir] [base] - or set TRAYCER_WEB_BASE",
    );
  }
  const mobileRoot = resolve(import.meta.dirname, "..");
  const distDir = resolve(mobileRoot, distArg);

  const html = await readFile(resolve(distDir, "index.html"), "utf8");
  const { collectEntryCriticalUrls } = await loadPrecacheList(mobileRoot);

  // A real absolute URL so relative hrefs resolve; the origin is discarded,
  // only the pathname survives into the list.
  const pageUrl = new URL(
    base.endsWith("/") ? base : `${base}/`,
    "https://sw.invalid",
  ).href;
  const precache = collectEntryCriticalUrls(html, pageUrl);

  // The document itself is the app shell and is never named by its own tags.
  const shell = new URL("index.html", pageUrl).pathname;
  if (!precache.includes(shell)) precache.push(shell);

  // A short list means the HTML parse found nothing - which is exactly how the
  // archived glob failed: quietly, shipping a worker that precached an
  // unbootable shell. Fail the build instead of writing that file.
  if (precache.length < 4) {
    throw new Error(
      `precache list has only ${precache.length} entries (${precache.join(", ")}) - ` +
        `expected at least the shell, the entry script, a stylesheet and the ` +
        `manifest. Did index.html's tag shape change?`,
    );
  }

  const { buildId, text, precache: sorted } = await buildServiceWorkerText(
    mobileRoot,
    precache,
  );
  await writeFile(resolve(distDir, "sw.js"), text, "utf8");

  process.stdout.write(
    `[sw] build ${buildId} - precaching ${sorted.length}: ${sorted.join(", ")}\n`,
  );
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
